### ISSUE TITLE
CRAN version archived?

### ISSUE THREAD

**Issue by IndrajeetPatil** [trinker/readability#6]
Hi,

I see that this R package has been archived on CRAN. I was using this package for my data analysis and I am now going to download it from Github. 

Was there any specific reason for which it was archived? Is it being replaced by something new?

Thanks.

**Comment by trinker** [comment]
Hi,

Good question.  I learned from Ken Benoit (quanteda) that he was working on
a better readaility package that spans multiple languages.  The readability
package has a long standing bug in the FOG Index:
https://github.com/trinker/readability/issues/4 that I just don't have the
devlopment time for.  Thie motivation for fixing this bug was lower due to
the fact that the package had low usership ( less than 200 downloads a
month).  Given all these things I felt with Ken's work that this would be a
good time to retire readability from CRAN and allow him to use that name if
he so chooses.

Tyler

**Comment by amarder** [comment]
Here's a link to Ken Benoit's package (quanteda): https://github.com/quanteda/quanteda

**Comment by trinker** [comment]
If I use R for readability stuff the quanteda is my go to, specifically: https://quanteda.io/reference/textstat_readability.html
